version: '3.9'

services:
  frontend:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
        - NEXT_PUBLIC_WS_URL_GRAMMER_SPELL=${NEXT_PUBLIC_WS_URL_GRAMMER_SPELL}
        - NEXT_PUBLIC_TASK_WS_URL=${NEXT_PUBLIC_TASK_WS_URL}
    container_name: lawvriksh-frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_WS_URL_GRAMMER_SPELL=${NEXT_PUBLIC_WS_URL_GRAMMER_SPELL}
      - NEXT_PUBLIC_TASK_WS_URL=${NEXT_PUBLIC_TASK_WS_URL}
    env_file:
      - .env
